name: notes_on_short
description: "A new Flutter project."


publish_to: 'none'













version: 1.0.0+1

environment:
  sdk: ^3.6.0







dependencies:
  flutter:
    sdk: flutter

  
  
  cupertino_icons: ^1.0.8
  firebase_core: ^3.10.0
  firebase_auth: ^5.4.0
  google_sign_in: ^6.2.2
  provider: ^6.1.2
  isar: ^3.1.0+1
  isar_flutter_libs: 3.1.0+1
  path_provider: ^2.1.5
  cloud_firestore: ^5.6.2
  connectivity_plus: ^6.1.2
  logger: ^2.5.0
  flutter_native_splash: ^2.4.4


dev_dependencies:
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.13
  flutter_test:
    sdk: flutter

  
  
  
  
  
  flutter_lints: ^5.0.0





flutter:

  
  uses-material-design: true

  
  assets:
    - assets/icons/
    - assets/images/
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
