name: notes_on_short
description: "A simple Notes application."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.10.0
  firebase_auth: ^5.4.0
  google_sign_in: ^6.2.2
  provider: ^6.1.2
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.5
  cloud_firestore: ^5.6.2
  connectivity_plus: ^6.1.2
  logger: ^2.5.0
  flutter_native_splash:
  flutter_launcher_icons:
  flutter_staggered_grid_view: ^0.7.0


dev_dependencies:
  isar_generator: ^3.1.0+1
  build_runner: any
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icons/icon.png"


flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/splash.png

  # These control image positioning
  android_gravity: center  # center, fill, etc.
  ios_content_mode: center  # center, scaleAspectFit, scaleAspectFill, etc.
  web_image_mode: center  # center, contain, stretch, etc.

  # Full screen mode (hides status bar)
  fullscreen: true

  # Android 12 specific settings
  android_12:
    image: assets/splash.png
    icon_background_color: "#FFFFFF"

  # Platform settings
  android: true
  ios: true
  web: false